backend:
  name: git-gateway
  branch: master
 
publish_mode: editorial_workflow
 
media_folder: "docs/.vuepress/public/upload"
public_folder: "/upload"
 
collections:
  - name: "documentation"
    label: "Documentation"
    folder: "docs/documentation"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}